spring:
  application:
    name: consumer-service-ribbon
  zipkin:
    base-url: http://mscloud-zipkin-service:8080
  boot:
    admin:
      client:
        url: http://mscloud-admin-service:2000

server:
  port: 9000

eureka:
  instance:
    hostname: mscloud-consumer-service-ribbon
  client:
    service-url:
      defaultZone: http://mscloud-eureka-server:7000/eureka/, http://mscloud-eureka-server:7001/eureka/, http://mscloud-eureka-server:7002/eureka/

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS